config/routes.rb
Rails.application.routes.draw do
  resources :students
 
  root 'students#index'
  
  

end

app/models/student.rb
class Student < ActiveRecord::Base
    belongs_to :school
    validates_presence_of :name
    validates :weight, :height, :gpa, :numericality => { :greater_than => 0,  :message=>"must be a positive number" } 
    validates :gpa, :numericality => { :less_than_or_equal_to => 4.33, :message=>"must be less than or equal to 4.33" }
    validates_each :name  do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :display]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end
  
  # GET '/students'
  # GET '/students.json'
  def display
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end
 
  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :weight, :height, :colour, :gpa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assigntwo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :GPA %><br>
    <%= f.text_field :gpa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/display.html.erb
<h1>Display of Students</h1>

<!---- DRAW STUDENTS HERE /--->
<table>
  <% @students.each do |student| %>
  <td> 
    <div style= "position:relative; width:<%=student.weight%>px;height:<%=student.height%>px; padding: 10px">
    <center><font size= "+3" color="<%=student.colour%>"><%=student.name%><br/> <%=student.gpa%> </font> </center>
    <img src="/stickman.png" alt="stickman" style="width:<%=student.weight%>px;height:<%=student.height%>px; border: solid 5px <%=student.colour%>;" />
    </div>
  </td>
  <% end %>
</table>



<%= link_to 'Back', students_path %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Colour</th>
      <th>GPA</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.weight %></td>
        <td><%= student.height %></td>
        <td><%= student.colour %></td>
        <td><%= student.gpa %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<!---link_to 'Draw all students', '/students/display' %>--->

<table>
  <% @students.each do |student| %>
  <td> 
    <div style= "position:relative; width:<%=student.weight%>px;height:<%=student.height%>px; padding: 10px">
    <center><font size= "+3" color="<%=student.colour%>"><%=student.name%><br/> <%=student.gpa%> </font> </center>
    <img src="/stickman.png" alt="stickman" style="width:<%=student.weight%>px;height:<%=student.height%>px; border: solid 5px <%=student.colour%>;" />
    </div>
  </td>
  <% end %>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @student.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @student.height %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @student.colour %>
</p>

<p>
  <strong>Gpa:</strong>
  <%= @student.gpa %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>
<br/>

<div style= "position:relative; width:<%=@student.weight%>px;height:<%=@student.height%>px; padding 10px">
  <center><font size= "+3" color="<%=@student.colour%>"><br/><%=@student.name%><br/> <%=@student.gpa%> </font> </center>
  <img src="/stickman.png" alt="stickman" style="width:<%=@student.weight%>px;height:<%=@student.height%>px; border: solid 5px <%=@student.colour%>;" />
</div>